runtime: python38
entrypoint: gunicorn -b :$PORT server:app

instance_class: B2 # 512 MB of RAM and 1.2 GHz CPU

manual_scaling:
  instances: 1 # Only 1 instance right now for low traffic and db using python