runtime: python
env: flex
entrypoint: gunicorn -b :$PORT server:app

runtime_config:
  python_version: 3.6

handlers:
- url: /static # TODO: find out if we really need this
  static_dir: static # TODO: find out if we really need this
- url: /.*
  script: server.app